### PR TITLE
fixed bug camera orientation closes #42

### LINKED ISSUE #42: Camera orientation, camera feed is upside down when rotating 270 deg

### PR DESCRIPTION
**Pull request by wkmeijer**
Added a orientationlistener that calls an already in place function that adjusts the camera preview. Screen rotation is a bit slower though...

Please check if the MRZ are still scanned correctly even in the case where the camera preview used to be upside down, I don't have a proper ID with readable MRZ here.

### CODE REVIEW

**Review by klikooo — APPROVED** [review]

File: app/src/main/java/com/digitalvotingpass/digitalvotingpass/Camera2BasicFragment.java [hunk 1]
```diff
@@ -675,6 +686,7 @@ private void configureTransform(int viewWidth, int viewHeight) {
         RectF bufferRect = new RectF(0, 0, mPreviewSize.getHeight(), mPreviewSize.getWidth());
         float centerX = viewRect.centerX();
         float centerY = viewRect.centerY();
+        Log.e(TAG, "Rotation: " + rotation);
```
Comment (jonathanraes) [inline app/src/main/java/com/digitalvotingpass/digitalvotingpass/Camera2BasicFragment.java:700]: this can go i guess

**Review by jonathanraes — COMMENTED** [review]
Works great

**Review by jonathanraes — APPROVED** [review]
